### ISSUE TITLE
[Feature]: Multiple select when searching for different types

### ISSUE THREAD

**Issue by deku-m** [Onemind-Services-LLC/netbox-metatype-importer#14]
### NetBox version

v3.4.5

### Feature type

Add a function

### Proposed functionality

When searching in the importer i notice when selecting a device you can select it but when you search for diffent device and select that one. When pressing the import selected only the last one will be added and not the one you also selected before.

**Example:** 
Search 9200-L, select one
Search 9500, select one.
Import Selected.

### Use case

Just nice to have so you dont have to go and search again and again and add it.

### External dependencies

None?

**Comment by abhi1693** [comment]
This may be how netbox handles the selection on the table. I doubt there is much I can implement to improve this.
