### ISSUE TITLE
[Feature]: Return to importer after adding device

### ISSUE THREAD

**Issue by deku-m** [Onemind-Services-LLC/netbox-metatype-importer#15]
### NetBox version

v3.4.5

### Feature type

Add a function

### Proposed functionality

When importing a device or module type. It immediatly goes to the device-type/moduletype overview.
But when you want to add more devices this might be unhandy as you need to switch back and forth.

### Use case

Nice to  have  more a user experience.

### External dependencies

None

**Comment by abhi1693** [comment]
I'm not sure how good this would be, as I personally like to be redirected so that I can access the types which have been imported
