### ISSUE TITLE
Add support for Netbox 3.7.x

### ISSUE THREAD

**Issue by litebito** [Onemind-Services-LLC/netbox-metatype-importer#35]
### Current NetBox Version

v3.7.0

### Feature Type

Modification to Existing Model

### Proposed Functionality

Change to existing model

### Use Case

A very recent release of netbox-metatype-importer to support Netbox v3.6.x was just released here https://github.com/Onemind-Services-LLC/netbox-metatype-importer/issues/26
But Netbox v3.7.0 was already released in the mean time (end of December: https://github.com/netbox-community/netbox/releases/tag/v3.7.0 ). 
 
Request: Update the plugin as per the NetBox v3.7 release

**Comment by abhi1693** [comment]
I think this should be a relatively small change as we don't expect to have any changes in the current version.

@kprince28 please raise a PR early tomorrow morning for this.
